/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_carlosfortin;

import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Carlos Fortin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        au.cargarArchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_registro = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_agrnombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sp_agredad = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        tf_agrcorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_agrusuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pf_agrpassword = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        tf_agrnomcanal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_agrcateg = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jd_menu = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_suscripciones = new javax.swing.JTree();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_misvideos = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        lb_nombre = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lb_sus = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_buscarCanales = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        tf_nombrevideo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        sp_duracion = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_subtitulos = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pop_reproducir = new javax.swing.JPopupMenu();
        reproducir = new javax.swing.JMenuItem();
        jd_reproducirVideo = new javax.swing.JDialog();
        lb_nomVid = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_subtitulosVid = new javax.swing.JTextArea();
        pb_vid = new javax.swing.JProgressBar();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        Tabla_comentarios = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        ta_comentarios = new javax.swing.JTextArea();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        lb_likes = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lb_dislikes = new javax.swing.JLabel();
        jd_reproducirPlayList = new javax.swing.JDialog();
        jScrollPane9 = new javax.swing.JScrollPane();
        ta_comPlay = new javax.swing.JTextArea();
        pb_durPlay = new javax.swing.JProgressBar();
        jScrollPane10 = new javax.swing.JScrollPane();
        Tabla_reproducciones = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pf_password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Registro");

        jLabel6.setText("Nombre");

        jLabel7.setText("Edad");

        sp_agredad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel8.setText("Correo");

        jLabel9.setText("Usuario");

        jLabel10.setText("Password");

        jLabel11.setText("Nombre Canal");

        jLabel12.setText("Categoria");

        jLabel13.setText("Canal");

        jLabel14.setText("Usuario");

        jButton3.setText("Registrarse");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_registroLayout = new javax.swing.GroupLayout(jd_registro.getContentPane());
        jd_registro.getContentPane().setLayout(jd_registroLayout);
        jd_registroLayout.setHorizontalGroup(
            jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_registroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_registroLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(292, 292, 292))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_registroLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(303, 303, 303))))
            .addGroup(jd_registroLayout.createSequentialGroup()
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_registroLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel5))
                    .addGroup(jd_registroLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_agrnombre)
                            .addGroup(jd_registroLayout.createSequentialGroup()
                                .addComponent(sp_agredad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(tf_agrcorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                            .addComponent(tf_agrusuario)
                            .addComponent(pf_agrpassword)
                            .addComponent(tf_agrnomcanal)
                            .addComponent(tf_agrcateg)))
                    .addGroup(jd_registroLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jButton3)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jd_registroLayout.setVerticalGroup(
            jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(70, 70, 70)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_agrnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sp_agredad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tf_agrcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_agrusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pf_agrpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_agrnomcanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_agrcateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(jButton3)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel15.setText("YouLeoTube");

        tab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabStateChanged(evt);
            }
        });

        jLabel17.setText("Mis Suscripciones");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Categorias");
        jt_suscripciones.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_suscripciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_suscripcionesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_suscripciones);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setText("Mis Videos");

        Tabla_misvideos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Duracion", "Likes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla_misvideos);

        jButton5.setText("Ver Favoritos");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jLabel20.setText("Nombre:");

        lb_nombre.setText("lb_nombre");

        jLabel21.setText("Suscriptores: ");

        lb_sus.setText("lb_sus");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(200, 200, 200))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_sus))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_nombre)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lb_nombre))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lb_sus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(15, 15, 15))
        );

        jLabel16.setText("Mi canal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(216, 216, 216))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        tab.addTab("Menu", jPanel1);

        Tabla_buscarCanales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Contenido", "Suscriptores"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Tabla_buscarCanales);

        jButton6.setText("Suscribirse");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(346, 346, 346))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        tab.addTab("Buscar Canales", jPanel2);

        jLabel19.setText("Nombre:");

        jLabel23.setText("Duracion:");

        sp_duracion.setModel(new javax.swing.SpinnerNumberModel(10, 10, null, 1));

        jLabel24.setText("segundos");

        jLabel25.setText("Subtitulos");

        ta_subtitulos.setColumns(20);
        ta_subtitulos.setRows(5);
        jScrollPane4.setViewportView(ta_subtitulos);

        jLabel26.setText("Ingresar los subtitulos de la forma:");

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setText("linea1;linea2;linea3...");

        jButton7.setText("Subir Video");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel23)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nombrevideo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(sp_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(jButton7))))
                .addContainerGap(494, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_nombrevideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(sp_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(30, 30, 30)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addGap(70, 70, 70)
                .addComponent(jButton7)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        tab.addTab("Subir Video", jPanel3);

        jButton4.setText("Cerrar Sesion");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_menuLayout = new javax.swing.GroupLayout(jd_menu.getContentPane());
        jd_menu.getContentPane().setLayout(jd_menuLayout);
        jd_menuLayout.setHorizontalGroup(
            jd_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuLayout.createSequentialGroup()
                .addGroup(jd_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_menuLayout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel15))
                    .addGroup(jd_menuLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jd_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4)
                            .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jd_menuLayout.setVerticalGroup(
            jd_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel15)
                .addGap(3, 3, 3)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        reproducir.setText("Reproducir");
        reproducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproducirActionPerformed(evt);
            }
        });
        pop_reproducir.add(reproducir);

        lb_nomVid.setText("Nombre_Vid");

        ta_subtitulosVid.setColumns(20);
        ta_subtitulosVid.setRows(5);
        jScrollPane6.setViewportView(ta_subtitulosVid);

        jButton8.setText("Like");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setText("Dislike");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        Tabla_comentarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Comentarios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(Tabla_comentarios);

        ta_comentarios.setColumns(20);
        ta_comentarios.setRows(5);
        jScrollPane8.setViewportView(ta_comentarios);

        jButton10.setText("Enviar Comentario");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jButton11.setText("Agregar a Favoritos");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jLabel22.setText("Likes:");

        lb_likes.setText("likes");

        jLabel28.setText("Dislikes:");

        lb_dislikes.setText("dislikes");

        javax.swing.GroupLayout jd_reproducirVideoLayout = new javax.swing.GroupLayout(jd_reproducirVideo.getContentPane());
        jd_reproducirVideo.getContentPane().setLayout(jd_reproducirVideoLayout);
        jd_reproducirVideoLayout.setHorizontalGroup(
            jd_reproducirVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_reproducirVideoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jd_reproducirVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10)
                    .addGroup(jd_reproducirVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jd_reproducirVideoLayout.createSequentialGroup()
                            .addComponent(jButton8)
                            .addGap(31, 31, 31)
                            .addComponent(jButton9)
                            .addGap(36, 36, 36)
                            .addComponent(jButton11))
                        .addGroup(jd_reproducirVideoLayout.createSequentialGroup()
                            .addComponent(lb_nomVid)
                            .addGap(172, 172, 172)
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lb_likes)
                            .addGap(46, 46, 46)
                            .addComponent(jLabel28)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lb_dislikes))
                        .addComponent(jScrollPane6)
                        .addComponent(pb_vid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                        .addComponent(jScrollPane8)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jd_reproducirVideoLayout.setVerticalGroup(
            jd_reproducirVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_reproducirVideoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jd_reproducirVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nomVid)
                    .addComponent(jLabel22)
                    .addComponent(lb_likes)
                    .addComponent(jLabel28)
                    .addComponent(lb_dislikes))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(pb_vid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jd_reproducirVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton11))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        ta_comPlay.setColumns(20);
        ta_comPlay.setRows(5);
        jScrollPane9.setViewportView(ta_comPlay);

        Tabla_reproducciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Canal", "Duracion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(Tabla_reproducciones);

        jLabel29.setText("Reproducciones");

        javax.swing.GroupLayout jd_reproducirPlayListLayout = new javax.swing.GroupLayout(jd_reproducirPlayList.getContentPane());
        jd_reproducirPlayList.getContentPane().setLayout(jd_reproducirPlayListLayout);
        jd_reproducirPlayListLayout.setHorizontalGroup(
            jd_reproducirPlayListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_reproducirPlayListLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jd_reproducirPlayListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addGroup(jd_reproducirPlayListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane9)
                        .addComponent(pb_durPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jd_reproducirPlayListLayout.setVerticalGroup(
            jd_reproducirPlayListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_reproducirPlayListLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pb_durPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("YouLeoTube");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Login");

        jLabel3.setText("Usuario");

        jLabel4.setText("Password");

        jButton1.setText("Ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Registrarse");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_usuario)
                            .addComponent(pf_password, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))))
                .addContainerGap(176, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(314, 314, 314))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(293, 293, 293))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(jButton1)
                .addGap(60, 60, 60)
                .addComponent(jButton2)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String nombre=tf_agrnombre.getText();
        int edad=(int)sp_agredad.getValue();
        String correo=tf_agrcorreo.getText();
        String usuario=tf_agrusuario.getText();
        String password=pf_agrpassword.getText();
        String nomcanal=tf_agrnomcanal.getText();
        String categ=tf_agrcateg.getText();
        
        boolean x=true;
        boolean y=true;
        
        for (Usuario u1 : au.getUsuarios()) {
            if(u1.getNombre().equals(nombre)){
                x=false;
                break;
            }
        }
        for (Usuario u2 : au.getUsuarios()) {
            if(u2.getCanal().getNombre().equals(nomcanal)){
                y=false;
                break;
            }
        }
        
        if(x && y){
            au.getUsuarios().add(new Usuario(nombre, edad, correo, usuario, new Canal(nomcanal, categ.toLowerCase()), password));
            au.escribirArchivo();
        }else{
            JOptionPane.showMessageDialog(jd_registro, "No pueden haber 2 usuarios con el mismo nombre o con el mismo canal");
        }
        
        tf_agrnombre.setText("");
        sp_agredad.setValue(1);
        tf_agrcorreo.setText("");
        tf_agrusuario.setText("");
        pf_agrpassword.setText("");
        tf_agrnomcanal.setText("");
        tf_agrcateg.setText("");
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jd_registro.setVisible(true);
        jd_registro.pack();
        jd_registro.setLocationRelativeTo(this);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String usuario=tf_usuario.getText();
        String password=pf_password.getText();
        boolean x=false;
        
        for (Usuario u1 : au.getUsuarios()) {
            if(u1.getUsuario().equals(usuario)){
                if(u1.getUsuario().equals(usuario) && u1.getPassword().equals(password)){
                    actual=u1;
                    x=true;
                    break;
                }
            }
        }
        
        if(x){
            jd_menu.setVisible(true);
            jd_menu.pack();
            jd_menu.setLocationRelativeTo(this);
            actualizarArbol();
            if(actual!=null){
                lb_nombre.setText(actual.getCanal().getNombre());
                lb_sus.setText(Integer.toString(actual.getCanal().getNo_sus()));
                actualizarTablaMisVideos();
            }
            JOptionPane.showMessageDialog(jd_menu, "Se ha ingresado con exito!");
        }else{
            JOptionPane.showMessageDialog(this, "Usuario o password incorrecta");
        }
        
        tf_usuario.setText("");
        pf_password.setText("");
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        if(tf_nombrevideo.getText().isEmpty() || ta_subtitulos.getText().isEmpty()){
        }else{
            //int cont=0;
            String nombre=tf_nombrevideo.getText();
            int duracion=(int)sp_duracion.getValue();
            String subtitulos=ta_subtitulos.getText()+";";
            int nosub=duracion/10;
            
            String[] sub=subtitulos.split(";");
            System.out.println(nosub+" "+sub.length);
            
            if(nosub==sub.length){
                actual.getCanal().getVideos().add(new Video(nombre));
                actual.getCanal().getVideos().get(actual.getCanal().getVideos().size()-1).setTiempo(duracion);
                actual.getCanal().getVideos().get(actual.getCanal().getVideos().size()-1).setSubtitulos(subtitulos);
                actual.getCanal().getVideos().get(actual.getCanal().getVideos().size()-1).setCanal(actual.getCanal());
                actualizarTablaMisVideos();
                au.escribirArchivo();
            }else{
                JOptionPane.showMessageDialog(jd_menu, "No se pudo crear video, los subtitulos no estan sincronizados");
            }
        }
        
        tf_nombrevideo.setText("");
        sp_duracion.setValue(10);
        ta_subtitulos.setText("");
        
    }//GEN-LAST:event_jButton7MouseClicked

    private void tabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabStateChanged
        if(tab.getSelectedIndex()==0){
            if(actual!=null){
                lb_nombre.setText(actual.getCanal().getNombre());
                lb_sus.setText(Integer.toString(actual.getCanal().getNo_sus()));
                actualizarTablaMisVideos();
            }
        }
        if(tab.getSelectedIndex()==1){
            if(actual!=null)
                actualizarTablaBuscarCanales();
        }
        if(tab.getSelectedIndex()==2){
            
        }
    }//GEN-LAST:event_tabStateChanged

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        if(Tabla_buscarCanales.getSelectedRow()>=0){
            String nom=Tabla_buscarCanales.getValueAt(Tabla_buscarCanales.getSelectedRow(), 0).toString();
            for (Usuario u : au.getUsuarios()) {
                if(u.getCanal().getNombre().equals(nom)){
                    temporal=u;
                }
            }
            
            if(temporal!=null){
                actual.getSuscripciones().add(temporal.getCanal());
                temporal.getCanal().addNo_sus();
                actualizarArbol();
                actualizarTablaBuscarCanales();
                au.escribirArchivo();
            }
            
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jt_suscripcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_suscripcionesMouseClicked
        if(evt.isMetaDown()){
            int row=jt_suscripciones.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_suscripciones.setSelectionRow(row);
            Object v1=jt_suscripciones.getSelectionPath().getLastPathComponent();
            seleccionado=(DefaultMutableTreeNode)v1;
            if(seleccionado.getUserObject() instanceof Video){
                repro=(Video)seleccionado.getUserObject();
                pop_reproducir.show(evt.getComponent(),evt.getX(),evt.getY());
            }
        }
    }//GEN-LAST:event_jt_suscripcionesMouseClicked

    private void reproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproducirActionPerformed
        rv=new ReproducirVideo(pb_vid, repro, ta_subtitulosVid);
        jd_reproducirVideo.setVisible(true);
        jd_reproducirVideo.pack();
        jd_reproducirVideo.setLocationRelativeTo(jd_menu);
        lb_nomVid.setText(repro.getNombre());
        lb_likes.setText(Integer.toString(repro.getLikesInt()));
        lb_dislikes.setText(Integer.toString(repro.getDislikesInt()));
        actualizarTablaComentarios();
        rv.start();
    }//GEN-LAST:event_reproducirActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        String comentario=actual.getUsuario()+":"+ta_comentarios.getText();
        repro.getComentarios().add(comentario);
        actualizarTablaComentarios();
        ta_comentarios.setText("");
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        if(repro.getLikes().contains(actual)){
            JOptionPane.showMessageDialog(jd_reproducirVideo, "Ya le diste like a este video");
        }else{
            repro.getLikes().add(actual);
            if(repro.getDislikes().contains(actual))
                repro.getDislikes().remove(actual);
            
            lb_likes.setText(Integer.toString(repro.getLikesInt()));
            lb_dislikes.setText(Integer.toString(repro.getDislikesInt()));
            au.escribirArchivo();
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        if(repro.getDislikes().contains(actual)){
            JOptionPane.showMessageDialog(jd_reproducirVideo, "Ya le diste dislike a este video");
        }else{
            repro.getDislikes().add(actual);
            if(repro.getLikes().contains(actual))
                repro.getLikes().remove(actual);
            
            lb_likes.setText(Integer.toString(repro.getLikesInt()));
            lb_dislikes.setText(Integer.toString(repro.getDislikesInt()));
            au.escribirArchivo();
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        if(actual.getFavoritos().getVideos().contains(repro)){
            JOptionPane.showMessageDialog(jd_reproducirVideo, "Este video ya esta en tus favoritos");
        }else{
            actual.getFavoritos().getVideos().add(repro);
            JOptionPane.showMessageDialog(jd_reproducirVideo, "Video agregado exitosamente");
            au.escribirArchivo();
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        if(actual.getFavoritos().getVideos().isEmpty()){
            JOptionPane.showMessageDialog(jd_menu, "No tienes videos favoritos");
        }else{
            rp=new ReproducirPlayList(actual.getFavoritos(), pb_durPlay, ta_comPlay, Tabla_reproducciones);
            jd_reproducirPlayList.setVisible(true);
            jd_reproducirPlayList.pack();
            jd_reproducirPlayList.setLocationRelativeTo(jd_menu);
            rp.start();
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        actual=null;
        jd_menu.setVisible(false);
    }//GEN-LAST:event_jButton4MouseClicked

    public void actualizarTablaMisVideos(){
        Tabla_misvideos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Duracion", "Likes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DefaultTableModel m=(DefaultTableModel)Tabla_misvideos.getModel();
        for (Video v : actual.getCanal().getVideos()) {
            Object[] info={v.getNombre(),v.getTiempo(),v.getLikesInt()};
            m.addRow(info);
        }
        Tabla_misvideos.setModel(m);
    }
    
    public void actualizarTablaBuscarCanales(){
        Tabla_buscarCanales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Contenido", "Suscriptores"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DefaultTableModel m=(DefaultTableModel)Tabla_buscarCanales.getModel();
        for (Usuario u : au.getUsuarios()) {
            boolean x=true;
            if(actual.getSuscripciones().contains(u.getCanal()) || actual.equals(u)){
                x=false;
            }
            
            if(x){
                Object[] info={u.getCanal().getNombre(),u.getCanal().getCategoria(),u.getCanal().getNo_sus()};
                m.addRow(info);
            }
            
        }
        Tabla_buscarCanales.setModel(m);
    }
    
    public void actualizarArbol(){
        if(actual!=null){
            javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Categorias");
            jt_suscripciones.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
            DefaultTreeModel m=(DefaultTreeModel)jt_suscripciones.getModel();
            root=(DefaultMutableTreeNode)m.getRoot();
            DefaultMutableTreeNode categ=null;
            
            for (Canal s : actual.getSuscripciones()) {
                if(root.getChildCount()==0){
                    categ=new DefaultMutableTreeNode(s.getCategoria());
                    DefaultMutableTreeNode canal=new DefaultMutableTreeNode(s);
                    if(s.getVideos().isEmpty()){
                    }else{
                        for (Video v : s.getVideos()) {
                            DefaultMutableTreeNode vid=new DefaultMutableTreeNode(v);
                            canal.add(vid);
                        }
                    }
                    categ.add(canal);
                    root.add(categ);
                }else{
                    boolean x=true;
                    int pos=0;
                    for (int i=0;i<root.getChildCount();i++) {
                        if(s.getCategoria().equals(root.getChildAt(i).toString())){
                            x=false;
                            System.out.println("false");
                            pos=i;
                            break;
                        }
                    }
                    
                    if(x){
                        categ=new DefaultMutableTreeNode(s.getCategoria());
                        DefaultMutableTreeNode canal=new DefaultMutableTreeNode(s);
                        if(s.getVideos().isEmpty()){
                        }else{
                            for (Video v : s.getVideos()) {
                                DefaultMutableTreeNode vid=new DefaultMutableTreeNode(v);
                                canal.add(vid);
                            }
                        }
                        categ.add(canal);
                        root.add(categ);
                    }else{
                        DefaultMutableTreeNode canal=new DefaultMutableTreeNode(s);
                        categ=(DefaultMutableTreeNode)root.getChildAt(pos);
                        if(s.getVideos().isEmpty()){
                        }else{
                            for (Video v : s.getVideos()) {
                                DefaultMutableTreeNode vid=new DefaultMutableTreeNode(v);
                                canal.add(vid);
                            }
                        }
                        categ.add(canal);
                        root.add(categ);
                    }
                    
                }
            }
            
        }
    }
    
    public void actualizarTablaComentarios(){
        if(repro!=null){
                
            Tabla_comentarios.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Comentarios"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class
                };
                boolean[] canEdit = new boolean [] {
                    false
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            
            if(repro.getComentarios().isEmpty()){
                
            }else{
                DefaultTableModel m=(DefaultTableModel)Tabla_comentarios.getModel();
                for (String c : repro.getComentarios()) {
                    String[] info={c};
                    m.addRow(info);
                }
                Tabla_comentarios.setModel(m);
            }
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_buscarCanales;
    private javax.swing.JTable Tabla_comentarios;
    private javax.swing.JTable Tabla_misvideos;
    private javax.swing.JTable Tabla_reproducciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JDialog jd_menu;
    private javax.swing.JDialog jd_registro;
    private javax.swing.JDialog jd_reproducirPlayList;
    private javax.swing.JDialog jd_reproducirVideo;
    private javax.swing.JTree jt_suscripciones;
    private javax.swing.JLabel lb_dislikes;
    private javax.swing.JLabel lb_likes;
    private javax.swing.JLabel lb_nomVid;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_sus;
    private javax.swing.JProgressBar pb_durPlay;
    private javax.swing.JProgressBar pb_vid;
    private javax.swing.JPasswordField pf_agrpassword;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JPopupMenu pop_reproducir;
    private javax.swing.JMenuItem reproducir;
    private javax.swing.JSpinner sp_agredad;
    private javax.swing.JSpinner sp_duracion;
    private javax.swing.JTextArea ta_comPlay;
    private javax.swing.JTextArea ta_comentarios;
    private javax.swing.JTextArea ta_subtitulos;
    private javax.swing.JTextArea ta_subtitulosVid;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTextField tf_agrcateg;
    private javax.swing.JTextField tf_agrcorreo;
    private javax.swing.JTextField tf_agrnombre;
    private javax.swing.JTextField tf_agrnomcanal;
    private javax.swing.JTextField tf_agrusuario;
    private javax.swing.JTextField tf_nombrevideo;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
    AdministrarUsuarios au=new AdministrarUsuarios("./usuarios.cafl");
    Usuario actual=null;
    Usuario temporal=null;
    Video repro=null;
    DefaultMutableTreeNode root=null;
    DefaultMutableTreeNode seleccionado=null;
    ReproducirVideo rv;
    ReproducirPlayList rp;
}
